### ISSUE TITLE
Normal string encryption

### ISSUE THREAD

**Issue by DmitryAsimov** [ItzSomebody/Radon#1]
It's a bit slow. Maybe try something else besides AES encryption?

**Comment by ItzSomebody** [comment]
Yup, known issue.

Have been meaning to work on it for awhile, but too lazy. Let me know if you have any suggestions.

**Comment by DmitryAsimov** [comment]
┬[┬GAMEMODE┬] ┬Usage: ┬/gamemode <0-3>
That happens when Unicode is used with AES

**Comment by ItzSomebody** [comment]
I suspected something like that might happen. Will rewrite normal transformer when I figure out what to do with it lol.

**Comment by DmitryAsimov** [comment]
Maybe something like allatori demo's string encryption would work? Because of the annoying ALLATORIXDEMO member names are annoying.

**Comment by Moonfield** [comment]
I agree with him I'm really poor to afford Allatori and I don't want the watermark If you can make Allatori's String Encryption would be cool!!!

**Comment by ItzSomebody** [comment]
Unfortunately, Allatori's string encryption is rather weak, thanks for the replies though!

**Comment by DmitryAsimov** [comment]
Oh ok can you make it like a string encryption called ultraweak then?

**Comment by Moonfield** [comment]
Can you make something like Stringer then cause Stringer is really good but It sadly got broken by Java Deobfuscator If you can make this IT WOULD BE GREAT!

**Comment by ItzSomebody** [comment]
@DmitryAsimov I guess, not sure if Allatori team would like me copying their algorithms though. ;)

@Moonfield Hmmm, I guess if I find some time.

**Comment by Moonfield** [comment]
Can you make Sandmark String Encryption? http://sandmark.cs.arizona.edu/ It's old and It's outdated maybe you can update it ^)

Input: 몫\uaacd被\uaacdﾑ⨐嵾⫷㢎量卮噋\udf7dꥊ뛎ು杨ἱ㗅붖궺鐺薳\ue8f8鈫堫Ⳓぱ幷⨜郒렢壵뺕ນ\udde1ㄽ띋彩ᙤ䋱洽뉌ꄝɴ滖邏唯檶엟耇폄㷑ﭚ쓓뮣髌┩皟䵹 < You can Deobf that with the DecodeString below and that Gets Generated when you do the Obfuscation ^-^

public static String DecodeString(final String arg0) {
		final StringBuffer sb = new StringBuffer(arg0.length() - 4);
		int n2 = arg0.charAt(0) << 24 | (arg0.charAt(1) & 'ÿ') << 16 | (arg0.charAt(2) & 'ÿ') << 8
				| (arg0.charAt(3) & 'ÿ');
		for (int i = 4; i < arg0.length(); ++i) {
			char c = '\0';
			char c2 = '耀';
			for (int j = 0; j < 16; ++j) {
				if ((n2 & 0x1) == 0x1) {
					n2 = ((n2 ^ 0x80000057) >> 1 | Integer.MIN_VALUE);
					c |= c2;
				} else {
					n2 >>= 1;
				}
				c2 >>= 1;
			}
			sb.append((char) (arg0.charAt(i) ^ c));
		}
		return new String(sb);
	}

**Comment by Moonfield** [comment]
also maybe you can take some tips from: http://www.sable.mcgill.ca/JBCO/examples.html to further improve your Flow and add more stuff :D

**Comment by Moonfield** [comment]
honestly jbco has some nice features https://imgur.com/a/imiR8 you may wanna take from it... Without giving credits ofc

**Comment by ItzSomebody** [comment]
The sandmark string encryption is a bit weak tbh (as are mine lol). Will definitely take a look though through the JBCO.

**Comment by Moonfield** [comment]
sandmark has more features just than String Encryption xd It has alot stuff like A LOT u might wanna take a look at It can complicate seriously so much

**Comment by DmitryAsimov** [comment]
what is classspliter in sandmark?

**Comment by ItzSomebody** [comment]
@Moonfield Ok, will take a look.

@DmitryAsimov from source code, it looks like it literally splits a class into several classes.

**Comment by DmitryAsimov** [comment]
Please make class encryption!

**Comment by Moonfield** [comment]
Something you don't wanna use LOL. Usually the good part is Buggy Code, Insert Opaque Predicates, Irreducibility, Opaque Branch Insertion, Promote Ptimitive Registers, Random Dead Code, String Encoder, Transparent Branch Inseriton.

**Comment by Moonfield** [comment]
Try these on Allatori's String Encryption for best results and compare before & after. xd

**Comment by Moonfield** [comment]
Anyway I need to go now XD Cya. (going to study fml)

**Comment by ItzSomebody** [comment]
Thanks for the suggestions @Moonfield 

**Buggy Code** is a little easy to remove because of the goto->label jump so I will not be implementing that.

**Insert Opaque Predicates** while interesting, I found this ineffectual against altering decompile results and will not be implemented.

**Irreducibility** sparked my interest and I might add this in the future.

**Opaque Branch Insertion** was still easy to read via a decompile.

**Promote Primitive Registers** still is very readable.

**Random Dead Code** while cool, does not affect decompiling and only make the method size (and ultimately the jar file bigger

**String Encoder** is a bit weak imo.

**Transparent Branch Insertion** while neat, does not affect decompiling by much.

I have yet to look at the JBCO project, so I will do that and consider what would be worthwhile adding.
