### ISSUE TITLE
[radon 3] NewArrayNode uses wrong operands (T_TYPE vs TYPE)

### ISSUE THREAD

**Issue by ItzSomebody** [ItzSomebody/radon#103]
Relevant: https://github.com/ItzSomebody/radon/blob/3653a55b3df87a7299026d497014f913e9895e8d/xyz.itzsomebody.codegen/src/main/java/xyz/itzsomebody/codegen/instructions/NewArrayNode.java#L35-L41

`WrappedType#getSort()` makes a call to `Type#getSort()` which will give the incorrect operand for the desired array type. This particular line needs to be fixed so `NewArrayNode` feeds `T_BYTE`, `T_INT`, `T_LONG`, etc. instead to `IntInsnNode`.

**Comment by Col-E** [comment]
Radon 3 not dead confirmed???

**Comment by ItzSomebody** [comment]
> Radon 3 not dead confirmed???

Might come back :)
