### ISSUE TITLE
renamer suggestion

### ISSUE THREAD

**Issue by apython123** [ItzSomebody/Radon#12]
Could you add name map file as renamer output ? This information should be needed in exception or debug . Thank you for "Radon" the greate job!

**Comment by ItzSomebody** [comment]
Added in recode

**Comment by qwertyuioasdfghj1212** [comment]
> Added in recode

我有个紧急的事要和您联系，希望得到您的帮助，麻烦您联系我一下：501803556@qq.com,多谢您了

**Comment by ItzSomebody** [comment]
> > Added in recode
> 
> 
> 
> 我有个紧急的事要和您联系，希望得到您的帮助，麻烦您联系我一下：501803556@qq.com,多谢您了

Feel free to email me at itzsomebody@protonmail.com.
