### ISSUE TITLE
Obfuscation corrupts the plugin due to annotations

### ISSUE THREAD

**Issue by kangarko** [ItzSomebody/Radon#16]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
0.8.1

**What kind of Jar file did you obfuscate?**
Premium plugin Boss.

**Any other information? (i.e. You combined Radon with other obfuscators)**
Used Proguard and ZKM before.

I would like to ask how to save the following error that is caused upon running a command in game, since each command class has an annotation on top of it. I have excluded the obfuscation of annotations completely in Proguard and ZKM, so I suspect here is a similar way as well, but I wonder what option causes this specifically. Thanks.

![a](https://i.imgur.com/Que66FY.png)

**Comment by kangarko** [comment]
Thanks! If it would be possible to make it work with that option, that would be sick

Lastly, I cannot seem to get the 0.8.2 working. When loading from a config, it always throws the "Spigot incompatibility with trash classes" warning even when that option is explicitly disabled, even to the point where all options are disabled.

**Comment by ItzSomebody** [comment]
Should be fixed in recode. Let me know if otherwise.

**Comment by kangarko** [comment]
@ItzSomebody that is really awesome!! Should I compile or is it still in works?
