### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by Olexorus** [ItzSomebody/Radon#17]
This is not important, but you could add a feature to specify the package name where all the obfuscated classes should be moved to, instead of just moving everything to the default package.

Also, I noticed that some classes are moved directly to the default package and some are moved to random packages with only a single class in it. I don't really understand the reason of this, does this improve the obfuscation?

**Comment by ItzSomebody** [comment]
Interesting ide

**Comment by ItzSomebody** [comment]
Interesting idea, I’ll consider it. 

To answer your question, there is no specific reason it is implement. Just random packages.

**Comment by ItzSomebody** [comment]
Closed this on accident, my bad.

**Comment by ItzSomebody** [comment]
Done in recode.
