### ISSUE TITLE
Renamer can break Jar Manifest

### ISSUE THREAD

**Issue by Olexorus** [ItzSomebody/Radon#18]
Radon version: 0.8.2
Transformers: Renamer

If there's a class called "Main", the renamer changes "Main-Class:" in the Manifest file to whatever the class was renamed to, for example "8X3Z-Class:" which breaks the Jar.

It doesn't matter if it's upper- or lowercase and probably (didn't test) also happens for other names like "Manifest", "Version", "Class" or in case of a Spigot Plugin "Description", "Author", "Website" etc.

**Comment by ItzSomebody** [comment]
This is actually an issue I found recently while testing with my private fork of Radon. Do you have any suggestions as to how I can fix such a particular replacement like this?

**Comment by Olexorus** [comment]
I don't work if this would work for everything, but since most types of config files use a ":" to seperate the keys from the values, you could check if there's at least one colon in each line and in case there is, exclude everything before the first colon from the renamer.

**Comment by ItzSomebody** [comment]
Fixed in recode.
