### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BeerFish** [ItzSomebody/Radon#19]
Version: 0.8.2

Spigot Fork

Transformers:
-Hide Code (But happens w/ everything)

The jar radon obfuscated.

https://hastebin.com/edotuguwem.css (The errors are on line 3 & 5. Line 4 is normal.)

This simply breaks the console in spigot. Unsure why this happens with every transformer I use.

**Comment by ItzSomebody** [comment]
AFAIK, this will happen without any plugins installed and any plugins installed. Can you please check if this is an issue with plugins or tacospigot itself?

**Comment by BeerFish** [comment]
Seems to be an issue with tacospigot itself. Tried with no plugins and it's the same result.

**Comment by ItzSomebody** [comment]
Alright, I'll close this for now.
