### ISSUE TITLE
JRE 9 & 10 compatibility

### ISSUE THREAD

**Issue by DrPiggy** [ItzSomebody/Radon#22]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)** 
Radon 0.8.2

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)** 
Standalone

**What transformers did you use which caused an error?**
* Transformer1
* Transformer2
* Transformer3
* etc.
Renamer

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
The jar

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)** 
https://hastebin.com/ihidumibeh.rb
**Any other information? (i.e. You combined Radon with other obfuscators)**
From java 9 forwards rt.jar does no longer exist, causing radon to not be able to rename for some reason.

Download for jar:
https://mega.nz/#!6VIkUCAQ!6N95kk49d-Gzw6zZCr3nd5Ms7YTWGyXWfNgxSC4H2lk

**Comment by ItzSomebody** [comment]
Use this: https://github.com/Storyyeller/jrt-extractor

**Comment by DrPiggy** [comment]
Thanks! that fixed a lot of problems with the other modules not recognizing some of the classpath, so now i can successfully obf the jar with all of the options enabled even on max (besides invoke dynamic, see footnote), but unfortunately this did not fix the renamer leaving me with the exact same log: https://hastebin.com/tinalopola.rb. Id still suggest for you to put that link ^ up on the readme to help other JDK9/10 users.

‡it seems that invokedynamic works fine when set to light, but normal and heavy make the obfuscated jar have a EXCEPTION_ACCESS_VIOLATION on launch and fatally crash. see: https://hastebin.com/iqogepaxar.shell
