### ISSUE TITLE
HELP ME (Need A Quick Fix Lol)

### ISSUE THREAD

**Issue by Apocalypse-303** [ItzSomebody/Radon#24]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
Radon 0.8.2

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Minecraft Client

**What transformers did you use which caused an error?**
* heavy flow obfuscation transformer

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
it is with radon I fixed my bugs and even tried to conform to radon

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
Here Is The Pastebin https://pastebin.com/NexwP57a

**Any other information? (i.e. You combined Radon with other obfuscators)**
No, I Did not Combine Lol Doing That Breaks Stuff Normally Also From What I Have Seen When the flow setting is set to light it is fine just when it goes higher it breaks

**Comment by ItzSomebody** [comment]
#20
