### ISSUE TITLE
Promblem when trying to use it.

### ISSUE THREAD

**Issue by freaky1337** [ItzSomebody/Radon#25]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
0.8.2
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
standalone
**What transformers did you use which caused an error?**
* I used the ones which are in the example cfg.

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
None of them, I guess
**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://pastebin.com/7EUbPbt0
**Any other information? (i.e. You combined Radon with other obfuscators)**
No

**Comment by freaky1337** [comment]
Oh dear! I was blind, thanks. But now I'm facing with the following when compiling: https://i.imgur.com/kc2l4rg.jpg

**Comment by ItzSomebody** [comment]
Add your dependencies to the libraries.

**Comment by freaky1337** [comment]
Like what dependency?

**Comment by ItzSomebody** [comment]
Anything your java application uses as an API
