### ISSUE TITLE
BuildHierarchy failed (NPE)

### ISSUE THREAD

**Issue by ImMichey** [ItzSomebody/Radon#33]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.2

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Standalone

**What transformers did you use which caused an error?**
Doesn't matter, it also crashes with and without any transformers

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
Radon itself

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://pastebin.com/JKfLeCFA

**Any other information? (i.e. You combined Radon with other obfuscators)**
I'm using Java 10. The needed rt.jar was generated with jft-extractor on GitHub.

**Comment by ItzSomebody** [comment]
My guess is that you are missing a dependency, I’ll make sure to add null checking some time in the future.
