### ISSUE TITLE
Can't obfuscate a Hello World project with the InvokeDynamic and the StringsEncryption transformers

### ISSUE THREAD

**Issue by mariolatiffathy** [ItzSomebody/Radon#34]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
- I downloaded v1.0.2 but the GUI title is v1.0.1
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
- Standalone
**What transformers did you use which caused an error?**
- Strings encryption
- InvokeDynamic

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
- I really don't know, my JAR file is a simple Hello World project - can this be strings & InvokeDynamic obfuscated

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
- https://pastebin.com/Uww1v2cc

**Any other information? (i.e. You combined Radon with other obfuscators)**
- I think that you've fixed those errors because someone opened the same issue ( Issue #31 ) - but the files are still v1.0.1 and not v1.0.2

**Comment by ItzSomebody** [comment]
It's a slightly different error. I'll look into it when I find some time.

**Comment by mariolatiffathy** [comment]
That's really great!

**Comment by ItzSomebody** [comment]
Should be fixed in latest commit.
