### ISSUE TITLE
An Error Happened

### ISSUE THREAD

**Issue by xiaonian233** [ItzSomebody/Radon#36]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.0
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Standalone
**What transformers did you use which caused an error?**

* Renaming.

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
java.lang.NullPointerException

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**

**Any other information? (i.e. You combined Radon with other obfuscators)**
turn on the renaming,load my jar radon 1.0.0 told me 
![image](https://user-images.githubusercontent.com/21072615/45250092-00b61c80-b35f-11e8-94b2-ba8fd57e61f4.png)

**Comment by ItzSomebody** [comment]
You're missing dependencies.

**Comment by xiaonian233** [comment]
I try to add dependencies but still dont work,radon 0.8.2 add the same dependencies can work
