### ISSUE TITLE
Error java.lang.RuntimeException

### ISSUE THREAD

**Issue by bertek41** [ItzSomebody/Radon#4]
Which version of Radon are you using? Latest

What kind of Jar file did you obfuscate? Spigot plugin

Config: https://pastebin.com/dRGf9Rka

Errors: https://pastebin.com/g1t7GSdR

Disabling Renamer solving the issue but is it a solution?

**Comment by ItzSomebody** [comment]
I don't think you are using the latest version. Line 211 in Renamer.java is a javadoc (fancy comment basically)

**Comment by bertek41** [comment]
Adding dependencies and spigot jar to libraries solved the issue thanks.

**Comment by bertek41** [comment]
Also i downloaded from [here](https://github.com/ItzSomebody/Radon/releases). How can i download the latest release?

**Comment by bertek41** [comment]
New errors :D : https://pastebin.com/Gjjg4PKz (Using 0.5.1)

**Comment by ItzSomebody** [comment]
Atm, compiling it yourself

**Comment by bertek41** [comment]
I don't have it too.

**Comment by ItzSomebody** [comment]
Let me know if this is present in the current version of Radon (0.6.0)
