### ISSUE TITLE
Catching Throwables

### ISSUE THREAD

**Issue by Olexorus** [ItzSomebody/Radon#41]
I noticed that you really often use `catch (Throwable t)` in your code, it's really bad practice to do that. You should be as specific with catch clauses as possible. Throwable will not only catch all exceptions (only RuntimeExceptions should be caught at all), but what's even worse, it will also catch Errors, which should never happen.

At first I assumed you were just lazy, but then I noticed that you also catch Throwables at blocks without any exceptions at all. So my questions is, why are you doing this?

**Comment by ItzSomebody** [comment]
The reason that Throwable catches everything is the exact reason I use it. For example:

```java
LoggerUtils.stdErr(String.format("Error writing class %s. Skipping.", classWrapper.classNode.name + ".class"));
t.printStackTrace();
```

This catches any unhandled errors that the ClassWriter might throw. The reason I want errors to be caught is because it can be possible reason of a faulty jar output.
