### ISSUE TITLE
Keep Class

### ISSUE THREAD

**Issue by KamThail** [ItzSomebody/Radon#42]
I want a Keep Class function!
You can added?
I like your Obfuscator

**Comment by ItzSomebody** [comment]
Hi there!

Sorry, you are going to be more specific as to what you want. What exactly do you want the "Keep Class" function to do?

**Comment by KamThail** [comment]
Skip Obfuscate Class

**Comment by ItzSomebody** [comment]
This already exists. The exclusions panel in the GUI or in the config is probably what you want.
