### ISSUE TITLE
Exclusions function doesn't work

### ISSUE THREAD

**Issue by TheMajster** [ItzSomebody/Radon#44]
Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed) latest release

Exclusions function doesn't work.
Added class is edited anyway

Exclusions:
    - "Global: me.exas.test.Addon"

**Comment by ItzSomebody** [comment]
1. You are excluding the class wrong. Check [this](https://github.com/ItzSomebody/Radon#Exclusions)
2. Please do not put "latest" as the Radon version as this makes it difficult to figure out which version of Radon this is attached to.

**Comment by TheMajster** [comment]
Okey, version 1.0.4
Im try this and doesnt work
Global: me/exas/test/Addon.*

**Comment by ItzSomebody** [comment]
The 1.0.4 release breaks on exclusions (see [this](https://github.com/ItzSomebody/Radon/commit/14aba4ab6b41721224e2a5e325bf8a0a58d69c40)) so you have you clone the repository and build the jar yourself or wait until I release a later jar.

**Comment by TheMajster** [comment]
In version 1.0.1 working this function but not on Crasher
