### ISSUE TITLE
UTF8 string too large !

### ISSUE THREAD

**Issue by sintanial** [ItzSomebody/Radon#45]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.4

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
library for android

**What transformers did you use which caused an error?**
* StringEncryption

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
radon issue

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://pastebin.com/GZxCx4Vx

**Any other information? (i.e. You combined Radon with other obfuscators)**
Failed to obfuscate long string

**Comment by ItzSomebody** [comment]
What happens when you exclude that particular class?

**Comment by sintanial** [comment]
It’s image encoded in base64, with size about 53kb, but I think after string obfuscation, size increased more then 65535
