### ISSUE TITLE
Android crashed on NumberObfuscation with Heavy mode

### ISSUE THREAD

**Issue by sintanial** [ItzSomebody/Radon#46]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.4
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Android
**What transformers did you use which caused an error?**
* NumberObfuscation

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
radon issue
**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
```
W/dalvikvm( 5590): VFY: register1 v2 type 17, wanted 5
W/dalvikvm( 5590): VFY:  rejecting opcode 0x6e at 0x000c
W/dalvikvm( 5590): VFY:  rejected Lcom/myapp/sdk/MyAppTerms;.off (Landroid/content/Context;)V
W/dalvikvm( 5590): Verifier rejected class Lcom/myapp/sdk/MyAppTerms;
D/AndroidRuntime( 5590): Shutting down VM
W/dalvikvm( 5590): threadid=1: thread exiting with uncaught exception (group=0xa65f1228)
E/AndroidRuntime( 5590): FATAL EXCEPTION: main
E/AndroidRuntime( 5590): java.lang.VerifyError: com/myapp/sdk/MyAppTerms
```
**Any other information? (i.e. You combined Radon with other obfuscators)**
It's reproduced only when NumberObfuscation is Heavy, in Normal or Light mode, worked fine !
And it's reproduced only on android version 4.1-5.0. On version 6+ worked fine !
You combined Radon with other obfuscators: With proguard only, but without proguard it's crashed too

**Comment by ItzSomebody** [comment]
The opcode 0x6e is an invokevirtual instruction (in dalvik) so I'm not really sure why you are getting said error.

**Comment by sintanial** [comment]
But is only on Heavy mode and only on android version 4.1-5.0
