### ISSUE TITLE
Feature Request: Inclusion

### ISSUE THREAD

**Issue by benpoulson** [ItzSomebody/Radon#47]
Hi, first of all I'd like to say thanks for the great project.

Secondly, Is it possible to do the inverse of the Exclusion config?
I have a fat jar with around 30 open-source libraries in it, but we only want to protect our own proprietary code. Is it possible to only run Radon on our own classes?

**Comment by Eyremba** [comment]
@benpoulson Please keep in mind that Radon is more for experimental purposes... The fact that it is open-source makes it even easier to deobfuscate its output. So you should never use it for proprietary purposes.

**Comment by ItzSomebody** [comment]
Yes.

`(?!putstuffhere).*`

The way this works is by inverting the regex match then padding it with .* to match trailing characters in the class name.

**Comment by benpoulson** [comment]
@Eyremba Thanks for the words of caution, we'll bear that in mind.

@ItzSomebody Ah damn, that seems obvious now. Thanks for the help!
