### ISSUE TITLE
Light String Encryption caching system flaw

### ISSUE THREAD

**Issue by visleaf** [ItzSomebody/Radon#49]
`String Encryption` in `Light` mode produces decryptor with simple caching system: before actual decrypting it looks up for already decrypted string in his own `HashMap` using encrypted string as a key, but this system has a little flaw: two different strings may be encrypted in the same result string using different keys, for example:
```
10 or \u000a ^ 28502 = 28508 or \u6f5c
70 or \u0046 ^ 28442 = 28508 or \u6f5c
```
, so string that was decrypted first will take place in cache and be returned every time, when decryptor will be asked about `\u6f5c`.

Don't blame me for storing single characters as strings, it can happen with any string! :)

I'm using self-compiled Radon (master, 37baffbee1568b183a372369bd22cbc3f31177bc) with standalone `.jar` file and only `String Encryption` transformer in `Light` mode.

**Comment by ItzSomebody** [comment]
The reason why I won't be looking into fixing this anytime soon is because:

1. Hopefully someone has the sense not to make one-char strings.
2. The likelihood of someone getting a collision is incredibly low with longer strings.

**Comment by ItzSomebody** [comment]
After thinking about this for a bit, I changed my mind. I'll put it on my todo list.
