### ISSUE TITLE
Flow: Normal Obfuscation Creates Issues

### ISSUE THREAD

**Issue by funkemunky** [ItzSomebody/Radon#5]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**

**What kind of Jar file did you obfuscate?**
A spigot anticheat.

**What transformers did you use which caused an error?**
* Flow: Normal

**Is Radon the issue or the jar Radon obfuscated the issue?**
The jar Radon obfuscated. The Flow obfuscation set to Normal screws up some of my checks, but once set back to Light it fixes it. It looks like it causes some latency, or isn't boding well with my multithreaded events.

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
None

**Any other information? (i.e. You combined Radon with other obfuscators)**
None.

**Comment by ItzSomebody** [comment]
So just latency, or a nasty stack trace/verify error?

**Comment by ItzSomebody** [comment]
Hmmm, lag caused by flow obf should be eventually optimized away by the JIT. Does this happen just during startup or the entire duration the server is being run?

**Comment by funkemunky** [comment]
No it's not lag, it's just a whole bunch of errors and it shitting on itself.

**Comment by ItzSomebody** [comment]
What kind of errors? VerifyError?
