### ISSUE TITLE
Watermarker

### ISSUE THREAD

**Issue by freeasbird** [ItzSomebody/Radon#50]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
Radon 1.0.4 

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Standalone Jar

**What transformers did you use which caused an error?**
* Transformer1
* Transformer2
* Transformer3
* etc.
Watermarker transformer cause the problem. When I disable the watermarker, there is no error

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
     [java] [12/26/2018-01:03:15] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:15] INFO: Running Renamer transformer.
     [java] [12/26/2018-01:03:15] INFO: Generating mappings.
     [java] [12/26/2018-01:03:22] INFO: Finished generated mappings. [6837ms]
     [java] [12/26/2018-01:03:22] INFO: Applying mappings.
     [java] [12/26/2018-01:03:22] INFO: Mapped 1632 members. [137ms]
     [java] [12/26/2018-01:03:22] INFO: Attempting to map class names in resources
     [java] [12/26/2018-01:03:22] INFO: Mapped 1 names in resources. [16ms]
     [java] [12/26/2018-01:03:22] INFO: Dumping mappings.
     [java] [12/26/2018-01:03:22] INFO: Finished dumping mappings at C:\code\vpnx4.0\mappings.txt. [22ms]
     [java] [12/26/2018-01:03:22] INFO: Finished running Renamer transformer. [7014ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Heavy number obfuscation transformer.
     [java] [12/26/2018-01:03:22] INFO: Obfuscated 19566 numbers.
     [java] [12/26/2018-01:03:22] INFO: Finished running Heavy number obfuscation transformer. [72ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Heavy string encryption transformer.
     [java] [12/26/2018-01:03:22] INFO: Encrypted 13816 strings.
     [java] [12/26/2018-01:03:22] INFO: Finished running Heavy string encryption transformer. [87ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Heavy flow obfuscation transformer.
     [java] [12/26/2018-01:03:22] INFO: Added 144853 fake jump sequences
     [java] [12/26/2018-01:03:22] INFO: Finished running Heavy flow obfuscation transformer. [190ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Member Shuffler transformer.
     [java] [12/26/2018-01:03:22] INFO: Shuffled 22229 members.
     [java] [12/26/2018-01:03:22] INFO: Finished running Member Shuffler transformer. [5ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Local variables transformer.
     [java] [12/26/2018-01:03:22] INFO: Removed 22118 local variables.
     [java] [12/26/2018-01:03:22] INFO: Finished running Local variables transformer. [8ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Line numbers transformer.
     [java] [12/26/2018-01:03:22] INFO: Removed 64281 line numbers.
     [java] [12/26/2018-01:03:22] INFO: Finished running Line numbers transformer. [31ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Source name transformer.
     [java] [12/26/2018-01:03:22] INFO: Removed 1644 source name attributes.
     [java] [12/26/2018-01:03:22] INFO: Finished running Source name transformer. [2ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Source debug transformer.
     [java] [12/26/2018-01:03:22] INFO: Removed 1644 source debug attributes.
     [java] [12/26/2018-01:03:22] INFO: Finished running Source debug transformer. [3ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Crasher transformer.
     [java] [12/26/2018-01:03:22] INFO: Finished running Crasher transformer. [1ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Hide code transformer.
     [java] [12/26/2018-01:03:22] INFO: Hid 22620 members.
     [java] [12/26/2018-01:03:22] INFO: Finished running Hide code transformer. [11ms]
     [java] [12/26/2018-01:03:22] INFO: ------------------------------------------------
     [java] [12/26/2018-01:03:22] INFO: Running Watermarker transformer.
     [java] Exception in thread "main" java.lang.IllegalArgumentException: bound must be greater than origin
     [java]     at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:378)
     [java]     at me.itzsomebody.radon.utils.RandomUtils.getRandomInt(RandomUtils.java:39)
     [java]     at me.itzsomebody.radon.transformers.miscellaneous.watermarker.Watermarker.transform(Watermarker.java:53)
     [java]     at me.itzsomebody.radon.Radon.lambda$executeTransformers$3(Radon.java:275)
     [java]     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
     [java]     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
     [java]     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
     [java]     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
     [java]     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
     [java]     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
     [java]     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
     [java]     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     [java]     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
     [java]     at me.itzsomebody.radon.Radon.executeTransformers(Radon.java:271)
     [java]     at me.itzsomebody.radon.Radon.partyTime(Radon.java:75)
     [java]     at me.itzsomebody.radon.CLI.startTheParty(CLI.java:78)
     [java]     at me.itzsomebody.radon.CLI.<init>(CLI.java:47)
     [java]     at me.itzsomebody.radon.Main.main(Main.java:57)
     [java] Java Result: 1

**Any other information? (i.e. You combined Radon with other obfuscators)**
Can you give some examples, to tell how to use the watermarker. :)

**Comment by ItzSomebody** [comment]
Yea, this has happened a lot to me in the past with various transformers because I was being an idiot when I made the RandomUtils class and never bothered to fix it, I’ll get to it if I find some time. Thanks!

**Comment by freeasbird** [comment]
I fixed the bug.  
I will submit the fix :))))))))
I also added new feature:
with new feature, the radon "Libraries: " can search sub-directories to search all *.jar

**Comment by freeasbird** [comment]
There is no error after my fix, but the output jar can't work.  When I disabled the watermarker feature, the output jar works fine.
So i think watermarker  maybe have other logic problem, not just RandomUtils(it's just program problem).   :)

**Comment by ItzSomebody** [comment]
Thanks for the fix! I'll also look into the watermarking problem if I find some time.
