### ISSUE TITLE
ByteToMessageDecoder is missing in the classpath

### ISSUE THREAD

**Issue by pxoss** [ItzSomebody/Radon#52]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.4
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
plugin
**What transformers did you use which caused an error?**
* Transformer1
* Transformer2
* Transformer3
* etc.
none
**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
Radon produces error
**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://hastebin.com/wuhisozori.sql
**Any other information? (i.e. You combined Radon with other obfuscators)**
Minecraft Client Jar

**Comment by ItzSomebody** [comment]
Add the appropriate library to radon’s class path.
