### ISSUE TITLE
MissingClassException

### ISSUE THREAD

**Issue by Xmonpl** [ItzSomebody/Radon#53]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
1.0.4
**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Standalone
**What transformers did you use which caused an error?**
* MissingClassException 

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)**
Radon
**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://pastebin.com/Sjn2rG79
**Any other information? (i.e. You combined Radon with other obfuscators)**
The application on is written on JavaFX.

**Comment by ItzSomebody** [comment]
Is that class in the provided library jars?

**Comment by Xmonpl** [comment]
Never mind.I'm just an idiot XD
