### ISSUE TITLE
Obfuscation error

### ISSUE THREAD

**Issue by Lolix777** [ItzSomebody/Radon#57]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**  i could use the recent or the oldest the error still occurs in all the versions

**What kind of Jar file did you obfuscate? (Android/Standalone/Plugin)**
Minecraft forge mod

**What transformers did you use which caused an error?**
it doesn't matter if i use a transformer or not it still occurs

**Is Radon the issue or the jar Radon obfuscated the issue? (if the obfuscated jar is the issue, make sure to provide the jar)** it's a very private project i don't feel like giving the jar but i can give you any information regarding it... i know that the error only occurs with mods that use darkstormapi mods that dont use darkstormapi can be obfuscated just fine.

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)** https://pastebin.com/aAkBvxMM

**Any other information? (i.e. You combined Radon with other obfuscators)**
never combined anything. this only happens with mods that use darkstormapi.. thing i find weird is that my friend is able to obfuscate his project which uses darkstorm but i'm not able to do so.. and he doesn't seem to know why

**Comment by ItzSomebody** [comment]
I need to know which specific version was used so I can correlate the exception to the codebase. If you can’t provide which git commit release you used, please at least provide the Radon version.

**Comment by THEREALWWEFAN231** [comment]
I can confirm i had a issue just like this, when i ran the obfuscated jar it would crash with a game
java.lang.VerifyError? Adding -noverify to the jvm fixed it, removing the class, LogOutSpot would fix the error, my code WHERE IT ERRORS, is, 

```java
@EventTarget
	  public void onPacketRecived(EventPacketRecieve event) {
		  if(this.mode.getValue().equalsIgnoreCase("Tab") && event.getPacket() instanceof SPacketPlayerListItem) {
			  SPacketPlayerListItem packet = (SPacketPlayerListItem) event.getPacket();
			  for (SPacketPlayerListItem.AddPlayerData entrie : packet.getEntries()) {
				  if(packet.getAction() == SPacketPlayerListItem.Action.ADD_PLAYER) {
					  onPlayerJoin(entrie.getProfile());
				  } if(packet.getAction() == SPacketPlayerListItem.Action.REMOVE_PLAYER) {
					  onPlayerLeave(entrie.getProfile());
				  }
			  }
		  }
	  }
``` 
weird thing is, if i remove that then run it, there would be another error in the same class, somewhere else.

```java
Initializing game

java.lang.VerifyError: Expecting a stackmap frame at branch target 109
Exception Details:
  Location:
    me/THEREALWWEFAN231/wwefan/Modules/LogOutSpot.onPacketRecived(Lme/THEREALWWEFAN231/wwefan/events/EventPacketRecieve;)V @20: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2a12 5dba 0355 0000 ba03 5800 0012 56ba
    0x0000010: 035b 0000 9900 592b ba03 6500 00c1 000a
    0x0000020: 9900 4d2b ba03 6800 00c0 000a 4d2c ba03
    0x0000030: 7200 00ba 0375 0000 4e2d ba03 7800 0099
    0x0000040: 002e 2dba 037b 0000 c000 083a 042c ba03
    0x0000050: 8300 00b2 0386 a600 032c ba03 8900 00b2
    0x0000060: 038b a600 03b2 0143 99ff d101 bfb1     

	at me.THEREALWWEFAN231.wwefan.Module.ModuleManger.<init>(ModuleManger.java:57)```

I was using the latest release, 1.0.5.

**Comment by ItzSomebody** [comment]
> I can confirm i had a issue just like this, when i ran the obfuscated jar it would crash with a game
> java.lang.VerifyError? Adding -noverify to the jvm fixed it, removing the class, LogOutSpot would fix the error, my code WHERE IT ERRORS, is,
> 
> ```java
> @EventTarget
> 	  public void onPacketRecived(EventPacketRecieve event) {
> 		  if(this.mode.getValue().equalsIgnoreCase("Tab") && event.getPacket() instanceof SPacketPlayerListItem) {
> 			  SPacketPlayerListItem packet = (SPacketPlayerListItem) event.getPacket();
> 			  for (SPacketPlayerListItem.AddPlayerData entrie : packet.getEntries()) {
> 				  if(packet.getAction() == SPacketPlayerListItem.Action.ADD_PLAYER) {
> 					  onPlayerJoin(entrie.getProfile());
> 				  } if(packet.getAction() == SPacketPlayerListItem.Action.REMOVE_PLAYER) {
> 					  onPlayerLeave(entrie.getProfile());
> 				  }
> 			  }
> 		  }
> 	  }
> ```
> 
> weird thing is, if i remove that then run it, there would be another error in the same class, somewhere else.
> 
> ```java
> Initializing game
> 
> java.lang.VerifyError: Expecting a stackmap frame at branch target 109
> Exception Details:
>   Location:
>     me/THEREALWWEFAN231/wwefan/Modules/LogOutSpot.onPacketRecived(Lme/THEREALWWEFAN231/wwefan/events/EventPacketRecieve;)V @20: ifeq
>   Reason:
>     Expected stackmap frame at this location.
>   Bytecode:
>     0x0000000: 2a12 5dba 0355 0000 ba03 5800 0012 56ba
>     0x0000010: 035b 0000 9900 592b ba03 6500 00c1 000a
>     0x0000020: 9900 4d2b ba03 6800 00c0 000a 4d2c ba03
>     0x0000030: 7200 00ba 0375 0000 4e2d ba03 7800 0099
>     0x0000040: 002e 2dba 037b 0000 c000 083a 042c ba03
>     0x0000050: 8300 00b2 0386 a600 032c ba03 8900 00b2
>     0x0000060: 038b a600 03b2 0143 99ff d101 bfb1     
> 
> 	at me.THEREALWWEFAN231.wwefan.Module.ModuleManger.<init>(ModuleManger.java:57)```
> 
> I was using the latest release, 1.0.5.
> ```

Please create a proper issue.
