### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by Lightcolour-666** [ItzSomebody/Radon#59]
[Radon-Chinese version.zip](https://github.com/ItzSomebody/Radon/files/2896476/Radon-Chinese.version.zip)
Chinese language

**Comment by CrackFileso** [comment]
STOP DOING THIS.PLS. ENOUGH OK??!!?

**Comment by Lightcolour-666** [comment]
> 
> 
> 停止做 this.pls 。足够好了 ！ ！?(STOP DOING THIS.PLS. ENOUGH OK??!!?)



> 
> 
> STOP DOING THIS.PLS. ENOUGH OK??!!?



> 
> 
> STOP DOING THIS.PLS. ENOUGH OK??!!?

why?

**Comment by xiaonian233** [comment]
You can be really annoying, you know.

**Comment by xiaonian233** [comment]
> why?

You can be really annoying, you know.

**Comment by Lightcolour-666** [comment]
😁
