### ISSUE TITLE
To json

### ISSUE THREAD

**Issue by Zaxar163** [ItzSomebody/Radon#66]
This is idea... Move configs to json, because via gson you can easy deserialize/serialize it.

**Comment by Zaxar163** [comment]
Also the config should has class-hierarchy structure.

**Comment by ItzSomebody** [comment]
> This is idea... Move configs to json, because via gson you can easy deserialize/serialize it.

So you can't serialize/deserialize yaml? I personally prefer yaml to json because it's easier to read and edit which is why I use it as the configuration system. Sorry, but I won't be moving the config system to json.

> Also the config should has class-hierarchy structure.

?
