### ISSUE TITLE
Not obfuscating method parameters

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [ItzSomebody/Radon#74]
**Description of Bug:** A methods parameter name isn't being renamed with renamer, example public void example(Test thisIsentGettingObfuscated){}

**Expected behavior:** public void example(Test randomName){}

**Radon version:** Master, might want to fix it for later

**Configuration:** Provide the ___***FULL***___ configuration used to produce
the error. If privacy is desired, the configuration can be privately DM'd to
ItzSomebody#9663 on Discord., there just an input, an output, libraries, NO EXCLUSIONs(i say that because in previous versions exclusions would cause this bug), and i have this
`
"renamer": {
        "adapt_these_resources": [],
        "repackage_name": "test"
    }
`

**Relevant errors:** nothing

**Screenshots:** 

**Reproduction steps:**
run the master with 
`"renamer": {
        "adapt_these_resources": [],
        "repackage_name": "test"
    }`

**Comment by ItzSomebody** [comment]
You are going to need to provide more details before I can do something. Could you provide the JAR you're obfuscating?

**Comment by ItzSomebody** [comment]
Edit: I wasn't paying attention and thought you were saying "Test" isn't being renamed.

Renaming local variables aren't supposed to be renamed. However, you can remove them with the Shrinker.

**Comment by THEREALWWEFAN231** [comment]
O, ok thank you

**Comment by THEREALWWEFAN231** [comment]
Ok, Shinker didn't work, this is my config(basically)
```
"shrinker": {
        "remove_inner_classes": true,
        "remove_local_variables": true,
        "remove_outer_method": true,
        "remove_signature": true,
        "remove_source_debug": true,
        "remove_source_file": true
    },
"renamer": {
        "adapt_these_resources": [],
        "repackage_name": "test",
        "dump_mappings": true
    }```
this picture does not have exclusions, ![withoutexclusions](https://user-images.githubusercontent.com/21975901/58448897-2edeb680-80be-11e9-9e3e-5266c9567a23.PNG) , as you can see it renames correctly.

this picture has a exclusion "me/THEREALWWEFAN231/wwefan/mixin.*", ![exclusions](https://user-images.githubusercontent.com/21975901/58448907-34d49780-80be-11e9-991f-34a42f3d0b4f.PNG) , and as you can see it is not renaming the fields, and the class I am testing with is not in mixin.*, also some constructor field names do not get renamed

Im just trying to rename them so someone cant see what they are, and sorry i cant give the jar, but im sure it happens with all exclusions

**Comment by ItzSomebody** [comment]
Make sure you read up on regex.
