### ISSUE TITLE
Renamer + TrashClasses Bug

### ISSUE THREAD

**Issue by lolka13372** [ItzSomebody/Radon#75]
After the classes Renamer + trash are obfuscated, a folder with an empty name is created. As a result, the original folder is not deleted. I do not know what the problem is.

![image](https://user-images.githubusercontent.com/50153944/57975595-a2086e80-79d4-11e9-96f1-0c334d3bd4ee.png)

![image](https://user-images.githubusercontent.com/50153944/57975598-afbdf400-79d4-11e9-9377-616745a58b91.png)

![image](https://user-images.githubusercontent.com/50153944/57975603-b9dff280-79d4-11e9-9dbf-b66f8146ce41.png)

**Comment by ItzSomebody** [comment]
Please use the correct bug report format.

**Comment by lolka13372** [comment]
Sorry

**Comment by ItzSomebody** [comment]
Read [this](https://superuser.com/questions/153165/what-does-represent-while-giving-path).

**Comment by lolka13372** [comment]
getConfig (). get Transformers (). add (0, new Trash Classes ());

I changed to getConfig (). getTransformers (). add (new TrashClasses ());

**Comment by ItzSomebody** [comment]
Shouldn't make a difference as I call Transformers.sort() on the ArrayList.

**Comment by lolka13372** [comment]
I removed Transformer.Sort because it causes me a mistake

**Comment by ItzSomebody** [comment]
That's probably why you got the issue.

**Comment by lolka13372** [comment]
java.lang.NullPointerException
	at ....transformers.Transformer.sort(Transformer.java:168)
	at ...Radon.run(Radon.java:69)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by ItzSomebody** [comment]
That's caused whenever a transformer's ExclusionType is null. Last one I found like that was the watermarker.

**Comment by lolka13372** [comment]
How fix?

**Comment by ItzSomebody** [comment]
By not returning null in getExclusionType

**Comment by lolka13372** [comment]
I set the ExclusionType.Watermarker
I get the same message

**Comment by ItzSomebody** [comment]
That error doesn't necessarily mean it's the watermarker transformer.

**Comment by lolka13372** [comment]
I checked all classes and did not find where this error could have been caused - only because of this I removed the Sort transformer

**Comment by ItzSomebody** [comment]
Just use a debugger

**Comment by lolka13372** [comment]
Debugger which is embedded in eclipse?
