### ISSUE TITLE
Jar Radon obfuscated crashed with the exception: "java.lang.NoSuchMethodError"

### ISSUE THREAD

**Issue by vxzhong** [ItzSomebody/Radon#8]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
0.6.1
**What kind of Jar file did you obfuscate?**
android

**What transformers did you use which caused an error?**
* Renamer

**Is Radon the issue or the jar Radon obfuscated the issue?**
The jar crashed with the exception: "java.lang.NoSuchMethodError"

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**

**Any other information? (i.e. You combined Radon with other obfuscators)**
1. if I turn off Renamer, everything works fine.
2. Adding Exempts to the entire package doesn't work, it crashed also.
3. The methods that throw "java.lang.NoSuchMethodError" are private.
4. If I change the private method to protect or public, everything works fine.

So only private methods are causing the exception.

**Comment by ItzSomebody** [comment]
This is probably due to radon not correcting reflection patterns. I'll see if I have time to implement this sometime, thanks.

**Comment by ItzSomebody** [comment]
Since this is based on an extremely outdated version of Radon, I'll be closing this for now. If anyone has a similar issue, please let me know. Thanks.
