### ISSUE TITLE
VerifyError after union catch statement processing

### ISSUE THREAD

**Issue by x0ark** [ItzSomebody/Radon#9]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
0.6.1

**What kind of Jar file did you obfuscate?**
Java application

**What transformers did you use which caused an error?**
No transformers enabled

**Is Radon the issue or the jar Radon obfuscated the issue?**

**What is the error produced? (Copy-and-paste error into [PasteBin](http://pastebin.com) or [HasteBin](http://hastebin.com) and link it here)**
https://hastebin.com/leweranexe.php
There is try{}catch(Exception e){} in this method

**Any other information? (i.e. You combined Radon with other obfuscators)**
Used after proguard (Only renaming done, dontshrink, dontoptimize, target: '8')

**Comment by ItzSomebody** [comment]
This is probably an issue with ASM

Not much I can do about that

**Comment by x0ark** [comment]
@ItzSomebody which version of ASM used in this project? May be updating them can fix it?

**Comment by ItzSomebody** [comment]
@x0ark 6.1 I think
